// ゲームデータ
const rawWordList = [
    { jp: "カレー", kana: "かれー", isEnglish: false },
    { jp: "おにぎり", kana: "おにぎり", isEnglish: false },
    { jp: "ラーメン", kana: "らーめん", isEnglish: false },
    { jp: "寿司", kana: "すし", isEnglish: false },
    { jp: "天ぷら", kana: "てんぷら", isEnglish: false },
    { jp: "うどん", kana: "うどん", isEnglish: false },
    { jp: "焼肉", kana: "やきにく", isEnglish: false },
    { jp: "ピザ", kana: "ぴざ", isEnglish: false },
    { jp: "みそ汁", kana: "みそしる", isEnglish: false },
    { jp: "刺身", kana: "さしみ", isEnglish: false },
    { jp: "納豆", kana: "なっとう", isEnglish: false },
    { jp: "猫", kana: "ねこ", isEnglish: false },
    { jp: "犬", kana: "いぬ", isEnglish: false },
    { jp: "パンダ", kana: "ぱんだ", isEnglish: false },
    { jp: "キリン", kana: "きりん", isEnglish: false },
    { jp: "ゾウ", kana: "ぞう", isEnglish: false },
    { jp: "空", kana: "そら", isEnglish: false },
    { jp: "海", kana: "うみ", isEnglish: false },
    { jp: "山", kana: "やま", isEnglish: false },
    { jp: "川", kana: "かわ", isEnglish: false },
    { jp: "太陽", kana: "たいよう", isEnglish: false },
    { jp: "雨", kana: "あめ", isEnglish: false },
    { jp: "雪", kana: "ゆき", isEnglish: false },
    { jp: "桜", kana: "さくら", isEnglish: false },
    { jp: "学校", kana: "がっこう", isEnglish: false },
    { jp: "先生", kana: "せんせい", isEnglish: false },
    { jp: "教室", kana: "きょうしつ", isEnglish: false },
    { jp: "鉛筆", kana: "えんぴつ", isEnglish: false },
    { jp: "ノート", kana: "のーと", isEnglish: false },
    { jp: "時計", kana: "とけい", isEnglish: false },
    { jp: "電話", kana: "でんわ", isEnglish: false },
    { jp: "傘", kana: "かさ", isEnglish: false },
    { jp: "靴", kana: "くつ", isEnglish: false },
    { jp: "電車", kana: "でんしゃ", isEnglish: false },
    { jp: "バス", kana: "ばす", isEnglish: false },
    { jp: "船", kana: "ふね", isEnglish: false },
    { jp: "世界", kana: "せかい", isEnglish: false },
    { jp: "未来", kana: "みらい", isEnglish: false },
    { jp: "夢", kana: "ゆめ", isEnglish: false },
    { jp: "日本", kana: "にほん", isEnglish: false },
    { jp: "りんご", kana: "りんご", isEnglish: false },
    { jp: "みかん", kana: "みかん", isEnglish: false },
    { jp: "いちご", kana: "いちご", isEnglish: false },
    { jp: "ぶどう", kana: "ぶどう", isEnglish: false },
    { jp: "メロン", kana: "めろん", isEnglish: false },
    { jp: "スイカ", kana: "すいか", isEnglish: false },
    { jp: "トマト", kana: "とまと", isEnglish: false },
    { jp: "ナス", kana: "なす", isEnglish: false },
    { jp: "ニンジン", kana: "にんじん", isEnglish: false },
    { jp: "パーティー", kana: "ぱーてぃー", isEnglish: false },
    { jp: "ティー", kana: "てぃー", isEnglish: false },
    { jp: "チョコレート", kana: "ちょこれーと", isEnglish: false },
    { jp: "アイスクリーム", kana: "あいすくりーむ", isEnglish: false },
    { jp: "ハンバーグ", kana: "はんばーぐ", isEnglish: false },
    { jp: "オムライス", kana: "おむらいす", isEnglish: false },
    { jp: "お好み焼き", kana: "おこのみやき", isEnglish: false },
    { jp: "スパゲッティ", kana: "すぱげってぃ", isEnglish: false },
    { jp: "サンドイッチ", kana: "さんどいっち", isEnglish: false },
    { jp: "フライドポテト", kana: "ふらいどぽてと", isEnglish: false },
    { jp: "ショートケーキ", kana: "しょーとけーき", isEnglish: false },
    { jp: "シュークリーム", kana: "しゅーくりーむ", isEnglish: false },
    { jp: "カブトムシ", kana: "かぶとむし", isEnglish: false },
    { jp: "クワガタムシ", kana: "くわがたむし", isEnglish: false },
    { jp: "ハムスター", kana: "はむすたー", isEnglish: false },
    { jp: "チンパンジー", kana: "ちんぱんじー", isEnglish: false },
    { jp: "コアラ", kana: "こあら", isEnglish: false },
    { jp: "ペンギン", kana: "ぺんぎん", isEnglish: false },
    { jp: "ヒマワリ", kana: "ひまわり", isEnglish: false },
    { jp: "チューリップ", kana: "ちゅーりっぷ", isEnglish: false },
    { jp: "消しゴム", kana: "けしごむ", isEnglish: false },
    { jp: "教科書", kana: "きょうかしょ", isEnglish: false },
    { jp: "運動会", kana: "うんどうかい", isEnglish: false },
    { jp: "卒業式", kana: "そつぎょうしき", isEnglish: false },
    { jp: "入学式", kana: "にゅうがくしき", isEnglish: false },
    { jp: "修学旅行", kana: "しゅうがくりょこう", isEnglish: false },
    { jp: "カレンダー", kana: "かれんだー", isEnglish: false },
    { jp: "歯ブラシ", kana: "はぶらし", isEnglish: false },
    { jp: "冷蔵庫", kana: "れいぞうこ", isEnglish: false },
    { jp: "洗濯機", kana: "せんたくき", isEnglish: false },
    { jp: "掃除機", kana: "そうじき", isEnglish: false },
    { jp: "電子レンジ", kana: "でんしれんじ", isEnglish: false },
    { jp: "スマートフォン", kana: "すまーとふぉん", isEnglish: false },
    { jp: "パソコン", kana: "ぱそこん", isEnglish: false },
    { jp: "新幹線", kana: "しんかんせん", isEnglish: false },
    { jp: "自転車", kana: "じてんしゃ", isEnglish: false },
    { jp: "飛行機", kana: "ひこうき", isEnglish: false },
    { jp: "パトカー", kana: "ぱとかー", isEnglish: false },
    { jp: "消防車", kana: "しょうぼうしゃ", isEnglish: false },
    { jp: "救急車", kana: "きゅうきゅうしゃ", isEnglish: false },
    { jp: "ありがとう", kana: "ありがとう", isEnglish: false },
    { jp: "ごめんなさい", kana: "ごめんなさい", isEnglish: false },
    { jp: "いただきます", kana: "いただきます", isEnglish: false },
    { jp: "ごちそうさま", kana: "ごちそうさま", isEnglish: false },
    { jp: "遊園地", kana: "ゆうえんち", isEnglish: false },
    { jp: "水族館", kana: "すいぞくかん", isEnglish: false },
    { jp: "動物園", kana: "どうぶつえん", isEnglish: false },
    { jp: "図書館", kana: "としょかん", isEnglish: false },
    { jp: "ミーティング", kana: "みーてぃんぐ", isEnglish: false },
    { jp: "ウェブサイト", kana: "うぇぶさいと", isEnglish: false },
    { jp: "エビチリソース", kana: "えびちりそーす", isEnglish: false },
    { jp: "ハンバーガーセット", kana: "はんばーがーせっと", isEnglish: false },
    { jp: "クリームシチュー", kana: "くりーむしちゅー", isEnglish: false },
    { jp: "ミネストローネ", kana: "みねすとろーね", isEnglish: false },
    { jp: "ペペロンチーノ", kana: "ぺぺろんちーの", isEnglish: false },
    { jp: "カルボナーラ", kana: "かるぼなーら", isEnglish: false },
    { jp: "ティラノサウルス", kana: "てぃらのさうるす", isEnglish: false },
    { jp: "トリケラトプス", kana: "とりけらとぷす", isEnglish: false },
    { jp: "アメリカザリガニ", kana: "あめりかざりがに", isEnglish: false },
    { jp: "オオサンショウウオ", kana: "おおさんしょううお", isEnglish: false },
    { jp: "ボールペン", kana: "ぼーるぺん", isEnglish: false },
    { jp: "シャープペンシル", kana: "しゃーぷぺんしる", isEnglish: false },
    { jp: "百科事典", kana: "ひゃっかじてん", isEnglish: false },
    { jp: "自由研究", kana: "じゆうけんきゅう", isEnglish: false },
    { jp: "学級委員", kana: "がっきゅういいん", isEnglish: false },
    { jp: "エアコンディショナー", kana: "えあこんでぃしょなー", isEnglish: false },
    { jp: "トイレットペーパー", kana: "といれっとぺーぱー", isEnglish: false },
    { jp: "ティッシュペーパー", kana: "てぃっしゅぺーぱー", isEnglish: false },
    { jp: "ドライヤー", kana: "どらいやー", isEnglish: false },
    { jp: "インターホン", kana: "いんたーほん", isEnglish: false },
    { jp: "ジェットコースター", kana: "じぇっとこーすたー", isEnglish: false },
    { jp: "メリーゴーランド", kana: "めりーごーらんど", isEnglish: false },
    { jp: "観覧車", kana: "かんらんしゃ", isEnglish: false },
    { jp: "一石二鳥", kana: "いっせきにちょう", isEnglish: false },
    { jp: "一期一会", kana: "いちごいちえ", isEnglish: false },
    { jp: "十人十色", kana: "じゅうにんといろ", isEnglish: false },
    { jp: "温故知新", kana: "おんこちしん", isEnglish: false },
    { jp: "五里霧中", kana: "ごりむちゅう", isEnglish: false },
    { jp: "一生懸命", kana: "いっしょうけんめい", isEnglish: false },
    { jp: "焼肉定食", kana: "やきにくていしょく", isEnglish: false },
    { jp: "コンビニエンスストア", kana: "こんびにえんすすとあ", isEnglish: false },
    { jp: "スーパーマーケット", kana: "すーぱーまーけっと", isEnglish: false },
    { jp: "デパートメントストア", kana: "でぱーとめんとすとあ", isEnglish: false },
    { jp: "プログラミング", kana: "ぷろぐらみんぐ", isEnglish: false },
    { jp: "アプリケーション", kana: "あぷりけーしょん", isEnglish: false },
    { jp: "インターネット", kana: "いんたーねっと", isEnglish: false },
    { jp: "コミュニケーション", kana: "こみゅにけーしょん", isEnglish: false },
    { jp: "インフォメーション", kana: "いんふぉめーしょん", isEnglish: false },
    { jp: "エンターテインメント", kana: "えんたーていんめんと", isEnglish: false },
    { jp: "リサイクル", kana: "りさいくる", isEnglish: false },
    { jp: "ボランティア", kana: "ぼらんてぃあ", isEnglish: false },
    { jp: "オリンピック", kana: "おりんぴっく", isEnglish: false },
    { jp: "パラリンピック", kana: "ぱらりんぴっく", isEnglish: false },
    { jp: "コミュニティ", kana: "こみゅにてぃ", isEnglish: false }
];

const difficultyConfig = {
    'easy':   { min: 2, max: 7,  time: 60,  label: '簡単' },
    'normal': { min: 5, max: 10, time: 90,  label: '普通' },
    'hard':   { min: 9, max: 14, time: 120, label: '難しい' }
};

const modeConfig = {
    'practice': { label: '練習', icon: 'fa-seedling', color: 'text-green-400' },
    'normal': { label: '普通', icon: 'fa-stopwatch', color: 'text-cyan-400' },
    'sudden_death': { label: '一発勝負', icon: 'fa-skull', color: 'text-red-400' }
};

// データ構造のバージョン管理
const DATA_VERSION = 1;
